### ISSUE TITLE
Add hashmap key to agreement autocomplete

### ISSUE THREAD

**Issue by tgrochowski** [BitBagCommerce/SyliusAgreementPlugin#6]
As discussed with @DominikWolos this is just a cosmetic change and it can wait to be done in a later stage.

_Originally posted by @er1z in https://github.com/BitBagCommerce/SyliusAgreementPlugin/pull/4#discussion_r773862108_

**Comment by liszkapawel** [comment]
Functionality will be added in the latest plugin version
